name: QuPath to CED

env:
  CED_ENVIRONMENT: development
  CED_CLI_TOKEN: ${{secrets.MERTHIN_TOKEN}}
  CED_PROJECT_PATH: qupath

on:
  push:
    branches:
      - master
    paths:
      - "alafia-qupath/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: MerthinTechnologies/push-ced-source-action@v1